# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-26 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
